### ISSUE TITLE
How to show a better format like Minutes:seconds and not only seconds?

### ISSUE THREAD

**Issue by ssoulless** [flyandi/meteor-reactive-countdown#1]
Hi, Im trying to figure out how to show a better format, right now it is only showing seconds left, but would be great if we can also format the countdown for show minutes, and seconds, even hours and so on.

**Comment by flyandi** [comment]
should be easy to implement. In the function `get` you just have to invoke the formatting. 

Currently I am just returning `this._current` which is the raw value for seconds but you could extend this with simple formatting, e.g.

```
var _hours = parseInt(this._current / 3600) % 24,
      _minutes = parseInt(this._current / 60) % 60;

return _hours + ":" + _minutes;
```

Fork it and try it out :-)

**Comment by ahmedtabrez** [comment]
@ssoulless, @flyandi, <a href="https://github.com/ahmedtabrez/meteor-reactive-countdown/commit/47be68d565a09697ec0ddfa1e433efabbd353bfd">latest commit at my fork of this project</a> addresses this problem. I have created a <a href="https://github.com/flyandi/meteor-reactive-countdown/pull/2">pull request</a> for the same. Hope that helps !

**Comment by flyandi** [comment]
Pull request approved.
