### ISSUE TITLE
Stops working in background

### ISSUE THREAD

**Issue by boxxa** [flyandi/meteor-reactive-countdown#5]
Anyone else see the issue in Chrome? If the countdown timer is running and you put the tab in the background, it will stop the timer essentially until you return and be out of sync.

**Comment by flyandi** [comment]
I think that's an actual issue of chrome that pauses all processes once you navigate away from the tab. The countdown timer doesn't create a timer on the backend and relies on the front-end timers.

**Comment by boxxa** [comment]
Yep. Did some digging and seems like Chrome has a 1000 ms limit on backgrounded workers. My script was running at 100ms and causing this to be blocked.

https://codereview.chromium.org/6577021
